import random
from dotenv import load_dotenv
import os

load_dotenv()

def which_api():
    api_run = os.getenv("RUN")
    return api_run


base_url = os.getenv("BASE_URL")

web_merchant_auth = os.getenv("WEB_MERCHANT_AUTH")
web_secret_auth = os.getenv("WEB_SECRET_AUTH")
web_auth = (web_merchant_auth,web_secret_auth)

web_api_url = os.getenv("WEB_API")


headers = {
    "Content-Type": "application/json",
    "Accept": "application/json",
    #"cf-connecting-ip":"49.207.180.255"

}
# WEB CRAWLING

web_initiate_url = os.getenv("WEB_INITIATE")
web_status_url = os.getenv("WEB_STATUS")
web_result_url = os.getenv("WEB_RESULT")
web_list_url = os.getenv("WEB_LIST")


























def getLine():

    line = "                                                                        "

    #line = "•·······························•·······························•"
    return line

def getDotLine():


    dotline = "•·······························•·······························•"
    return dotline

def getweburl():

    urls = [
     "https://www.google.com",
    "https://www.github.com",
    "https://www.amazon.com",
    "https://www.nytimes.com",
    "https://www.wikipedia.org",
    "https://www.cnn.com",
    "https://www.apple.com",
    "https://www.microsoft.com",
    "https://www.youtube.com",
    "https://www.facebook.com",
    "https://www.instagram.com",
    "https://www.twitter.com",
    "https://www.linkedin.com",
    "https://www.reddit.com",
    "https://www.stackoverflow.com",
    "https://www.netflix.com",
    "https://www.spotify.com",
    "https://www.pinterest.com",
    "https://www.tumblr.com",
    "https://www.yahoo.com",
    "https://www.bing.com",
    "https://www.wikipedia.com",
    "https://www.nasa.gov",
    "https://www.bbc.com",
    "https://www.duckduckgo.com",
    "https://www.quora.com",
    "https://www.dropbox.com",
    "https://www.medium.com",
    "https://www.twitch.tv",
    "https://www.wikipedia.org",
    "https://www.ebay.com",
    "https://www.aliexpress.com",
    "https://www.walmart.com",
    "https://www.target.com",
    "https://www.bestbuy.com",
    "https://www.homedepot.com",
    "https://www.lowes.com",
    "https://www.costco.com",
    "https://www.alibaba.com",
    "https://www.booking.com",
    "https://www.expedia.com",
    "https://www.airbnb.com",
    "https://www.zillow.com",
    "https://www.trulia.com",
    "https://www.realtor.com",
    "https://www.reuters.com",
    "https://www.bloomberg.com",
    "https://www.wsj.com",
    "https://www.ft.com",
    "https://www.economist.com",
    "https://www.forbes.com",
    "https://www.businessinsider.com",
    "https://www.cnbc.com",
    "https://www.buzzfeed.com",
    "https://www.techcrunch.com",
    "https://www.engadget.com",
    "https://www.arstechnica.com",
    "https://www.wired.com",
    "https://www.theverge.com",
    "https://www.mashable.com",
    "https://www.cnet.com",
    "https://www.pcworld.com",
    "https://www.tomsguide.com",
    "https://www.gamespot.com",
    "https://www.ign.com",
    "https://www.polygon.com",
    "https://www.kotaku.com",
    "https://www.eurogamer.net",
    "https://www.bbcgoodfood.com",
    "https://www.allrecipes.com",
    "https://www.foodnetwork.com",
    "https://www.epicurious.com",
    "https://www.bonappetit.com",
    "https://www.delish.com",
    "https://www.seriouseats.com",
    "https://www.foodandwine.com",
    "https://www.cooksillustrated.com",
    "https://www.myrecipes.com",
    "https://www.simplyrecipes.com",
    "https://www.thekitchn.com",
    "https://www.recipe.com",
    "https://www.skinnytaste.com",
    "https://www.bettycrocker.com",
    "https://www.kingarthurflour.com",
    "https://www.bbcgoodfood.com",
    "https://www.bbc.com",
    "https://www.news.sky.com",
    "https://www.itv.com",
    "https://www.channel4.com",
    "https://www.channel5.com",
    "https://www.nationalgeographic.com",
    "https://www.discovery.com",
    "https://www.smithsonianmag.com",
    "https://www.popsci.com",
    "https://www.scientificamerican.com",
    "https://www.nature.com",
    "https://www.newscientist.com",
    "https://www.nasa.gov",
    "https://www.worldbank.org",
    "https://www.space.com",
    "https://www.un.org",
    "https://www.futureplay.in/",
    "https://www.faretobaby.com/",
    "https://www.ibrow.in/",
    "https://www.pantechelearning.com/",
    "https://www.youthvillehostel.com/",
    "https://www.stownest.com/",
    "https://www.technosport.in/",
    "https://www.fuelled.in/",
    "https://www.asmitapatel.com/",
    "https://www.fitness2flash.com/",
    "https://www.yashhln.wixsite.com/",
    "https://www.rahulmalodia.com/",
    "https://www.dipanshuvijay.com/",
    "https://www.jainfuturisticacademy.com/",
    "https://www.purushottamaggarwal.com/",
    "https://www.gonatureclassrooms.org/",
    "https://www.beyondenough.in/",
    "https://www.sloshout.com/",
    "https://www.coachbsr.com/",
    "https://www.researchalert.in/",
    "https://www.anandaindia.org/",
    "https://www.novaananth.com/",
    "https://www.mrsindia.co/",
    "https://www.igiaviationdelhi.com/",
    "https://www.medigrad.com/",
    "https://www.guarented.com/",
    "https://www.tan365.in/",
    "https://www.bsiacademy.in/",
    "https://www.mytadoba.org/",
    "https://www.smsrampur.com/",
    "https://www.thebigredgroup.com/",
    "https://www.selfpractice.yogashowstheway.com/",
    "https://www.smartmove.co.in/",
    "https://www.ubtpro.in/",
    "https://www.playspots.in/",
    "https://www.eduxoncabs.com/",
    "https://www.myonlineca.in/",
    "https://www.imare.in/",
    "https://www.aksharyogaonline.com/",
    "https://www.clatapult.com/",
    "https://www.sharebazarexpert.com/",
    "https://www.purplepatchfarms.in/",
    "https://www.qualityhubindia.com/",
    "https://www.askiitians.com/",
    "https://www.pachaa.in/",
    "https://www.manishvermaofficial.com/",
    "https://www.issuewire.com/",
    "https://www.quantsgrow.com/",
    "https://www.utpalkc.com/",
    "https://www.giftstoindia24x7.com/",
    "https://www.vriksham.in/",
    "https://www.ebizfiling.com/",
    "https://www.shreetraining.com/",
    "https://www.blisspointstudies.com/",
    "https://www.fivevidya.com/",
    "https://www.thirdbell.in/",
    "https://www.speakify.com/",
    "https://www.shankarkulkarni.com/",
    "https://www.usedbooksfactory.com/",
    "https://www.taubsolutions.com/",
    "https://www.academy.codingrad.com/",
    "https://www.decorpot.com/",
    "https://www.carajaclasses.com/",
    "https://www.anooplifemanagementacademy.com/",
    "https://www.prorsi.com/",
    "https://www.smsrampur.com/",
    "https://www.sharan-india.org/",
    "https://www.theporter.in/",
    "https://www.shreedembla.com/",
    "https://www.tdspro.in/",
    "https://www.bni-puneeast.in/",
    "https://www.bni-chennaicbda.in/",
    "https://www.kingresearch-financial.mojo.page/",
    "https://www.engineercore.in/",
    "https://www.stxaviersschoolbangalore.com/",
    "https://www.winningteam.in/",
    "https://www.exposysdata.com/",
    "https://www.stockhifi.com/",
    "https://www.ijsrem.com/",
    "https://www.tathhastu.in/",
    "https://www.iamkshitijthorat.com/",
    "https://www.spayee.com/",
    "https://www.jbsacademy.com/",
    "https://www.apnagharashram.org/",
    "https://www.eleation.com/",
    "https://www.uniklife.com/",
    "https://www.virtualracinghub.com/",
    "https://www.investingdaddy.com/",
    "https://www.nitizsharma.com/",
    "https://www.ashaashta.com/",
    "https://www.kaizeninfotech.com/",
    "https://www.saurabhbajaj.in/",
    "https://www.globehost.com/",
    "https://www.quantifiers.in/",
    "https://www.imi.edu.in/",
    "https://www.newgenmax.com/",
    "https://www.marcscoffees.com/",
    "https://www.ijritcc.org/",
     "https://www.utpalkc.com/",
    "https://www.giftstoindia24x7.com/",
    "https://www.vriksham.in/",
    "https://www.ebizfiling.com/",
    "https://www.shreetraining.com/",
    "https://www.blisspointstudies.com/",
    "https://www.fivevidya.com/",
    "https://www.thirdbell.in/",
    "https://www.speakify.com/",
    "https://www.shankarkulkarni.com/",
    "https://www.usedbooksfactory.com/",
    "https://www.taubsolutions.com/",
    "https://www.academy.codingrad.com/",
    "https://www.decorpot.com/",
    "https://www.carajaclasses.com/",
    "https://www.anooplifemanagementacademy.com/",
    "https://www.prorsi.com/",
    "https://www.smsrampur.com/",
    "https://www.sharan-india.org/",
    "https://www.theporter.in/",
    "https://www.shreedembla.com/",
    "https://www.tdspro.in/",
    "https://www.bni-puneeast.in/",
    "https://www.bni-chennaicbda.in/",
    "https://www.kingresearch-financial.mojo.page/",
    "https://www.engineercore.in/",
    "https://www.stxaviersschoolbangalore.com/",
    "https://www.winningteam.in/",
    "https://www.exposysdata.com/",
    "https://www.stockhifi.com/",
    "https://www.ijsrem.com/",
    "https://www.tathhastu.in/",
    "https://www.iamkshitijthorat.com/",
    "https://www.spayee.com/",
    "https://www.jbsacademy.com/",
    "https://www.apnagharashram.org/",
    "https://www.eleation.com/",
    "https://www.uniklife.com/",
    "https://www.virtualracinghub.com/",
    "https://www.investingdaddy.com/",
    "https://www.nitizsharma.com/",
    "https://www.ashaashta.com/",
    "https://www.kaizeninfotech.com/",
    "https://www.saurabhbajaj.in/",
    "https://www.globehost.com/",
    "https://www.quantifiers.in/",
    "https://www.imi.edu.in/",
    "https://www.newgenmax.com/",
    "https://www.marcscoffees.com/",
    "https://www.ijritcc.org/",
     "https://www.futureplay.in/",
    "https://www.faretobaby.com/",
    "https://www.ibrow.in/",
    "https://www.pantechelearning.com/",
    "https://www.youthvillehostel.com/",
    "https://www.stownest.com/",
    "https://www.technosport.in/",
    "https://www.fuelled.in/",
    "https://www.asmitapatel.com/",
    "https://www.fitness2flash.com/",
    "https://www.yashhln.wixsite.com/",
    "https://www.rahulmalodia.com/",
    "https://www.dipanshuvijay.com/",
    "https://www.jainfuturisticacademy.com/",
    "https://www.purushottamaggarwal.com/",
    "https://www.gonatureclassrooms.org/",
    "https://www.beyondenough.in/",
    "https://www.sloshout.com/",
    "https://www.coachbsr.com/",
    "https://www.researchalert.in/",
    "https://www.anandaindia.org/",
    "https://www.novaananth.com/",
    "https://www.mrsindia.co/",
    "https://www.igiaviationdelhi.com/",
    "https://www.medigrad.com/",
    "https://www.guarented.com/",
    "https://www.tan365.in/",
    "https://www.bsiacademy.in/",
    "https://www.mytadoba.org/",
    "https://www.smsrampur.com/",
    "https://www.thebigredgroup.com/",
    "https://www.selfpractice.yogashowstheway.com/",
    "https://www.smartmove.co.in/",
    "https://www.ubtpro.in/",
    "https://www.playspots.in/",
    "https://www.eduxoncabs.com/",
    "https://www.myonlineca.in/",
    "https://www.imare.in/",
    "https://www.aksharyogaonline.com/",
    "https://www.clatapult.com/",
    "https://www.sharebazarexpert.com/",
    "https://www.purplepatchfarms.in/",
    "https://www.qualityhubindia.com/",
    "https://www.askiitians.com/",
    "https://www.pachaa.in/",
    "https://www.manishvermaofficial.com/",
    "https://www.issuewire.com/",
    "https://www.quantsgrow.com/",
     "https://www.amazon.com/",
    "https://www.ebay.com/",
    "https://www.walmart.com/",
    "https://www.etsy.com/",
    "https://www.target.com/",
    "https://www.bestbuy.com/",
    "https://www.alibaba.com/",
    "https://www.flipkart.com/",
    "https://www.homedepot.com/",
    "https://www.zappos.com/",
    "https://www.wayfair.com/",
    "https://www.overstock.com/",
    "https://www.asos.com/",
    "https://www.costco.com/",
    "https://www.macys.com/",
    "https://www.nordstrom.com/",
    "https://www.kohls.com/",
    "https://www.newegg.com/",
    "https://www.rakuten.com/",
    "https://www.shopdisney.com/",
    "https://www.qvc.com/",
    "https://www.aliexpress.com/",
    "https://www.banggood.com/",
    "https://www.lowes.com/",
    "https://www.sears.com/",
    "https://www.staples.com/",
    "https://www.samsclub.com/",
    "https://www.cvs.com/",
    "https://www.walgreens.com/",
    "https://www.grainger.com/",
    "https://www.groupon.com/",
    "https://www.1stdibs.com/",
    "https://www.rei.com/",
    "https://www.poshmark.com/",
    "https://www.crateandbarrel.com/",
    "https://www.bedbathandbeyond.com/",
    "https://www.chewy.com/",
    "https://www.autozone.com/",
    "https://www.advanceautoparts.com/",
    "https://www.petco.com/",
    "https://www.petsmart.com/",
    "https://www.dollartree.com/",
    "https://www.dollargeneral.com/",
    "https://www.michaels.com/",
    "https://www.dickssportinggoods.com/",
    "https://www.academy.com/",
    "https://www.basspro.com/",
    "https://www.cabelas.com/",
    "https://www.gamestop.com/",
    "https://www.footlocker.com/",
    "https://www.finishline.com/",
    "https://www.urbanoutfitters.com/",
    "https://www.patagonia.com/",
    "https://www.abercrombie.com/",
    "https://www.hollisterco.com/",
    "https://www.forever21.com/",
    "https://www.hm.com/",
    "https://www.uniqlo.com/",
    "https://www.ae.com/",
    "https://www.underarmour.com/",
    "https://www.nike.com/",
    "https://www.adidas.com/",
    "https://www.lululemon.com/",
    "https://www.athleta.com/",
    "https://www.oldnavy.com/",
    "https://www.gap.com/",
    "https://www.bananarepublic.com/",
    "https://www.express.com/",
    "https://www.jcrew.com/",
    "https://www.ralphlauren.com/",
    "https://www.burberry.com/",
    "https://www.coach.com/",
    "https://www.michaelkors.com/",
    "https://www.katespade.com/",
    "https://www.tiffany.com/",
    "https://www.gucci.com/",
    "https://www.prada.com/",
    "https://www.louisvuitton.com/",
    "https://www.chanel.com/",
    "https://www.cartier.com/",
    "https://www.rolex.com/",
    "https://www.omegawatches.com/",
    "https://www.fossil.com/",
    "https://www.citizenwatch.com/",
    "https://www.swatch.com/",
    "https://www.tissotwatches.com/",
    "https://www.movado.com/",
    "https://www.invictastores.com/",
    "https://www.casio.com/",
    "https://www.garmin.com/",
    "https://www.fitbit.com/",
    "https://www.bose.com/",
    "https://www.sonos.com/",
    "https://www.harmanaudio.com/",
    "https://www.marshall.com/",
    "https://www.sennheiser.com/",
    "https://www.skullcandy.com/",
    "https://www.jbl.com/",
    "https://www.bang-olufsen.com/"
    
]


    return urls
    

def gettrade():
    names = [
         "Apple Inc.",
    "Microsoft Corporation",
    "Amazon.com, Inc.",
    "Alphabet Inc.",
    "Tesla, Inc.",
    "Meta Platforms, Inc.",
    "Facebook, Inc.",
    "Alibaba Group Holding Limited",
    "Tencent Holdings Limited",
    "Johnson & Johnson",
    "Procter & Gamble Co",
    "JPMorgan Chase & Co.",
    "Walmart Inc.",
    "Berkshire Hathaway Inc.",
    "Visa Inc.",
    "Intel Corporation",
    "Cisco Systems, Inc.",
    "Netflix, Inc.",
    "Walt Disney Company",
    "Nike, Inc.",
    "McDonald's Corporation",
    "Coca-Cola Company",
    "Pfizer Inc.",
    "General Electric Company",
    "Boeing Company",
    "Exxon Mobil Corporation",
    "Chevron Corporation",
    "Verizon Communications Inc.",
    "AT&T Inc.",
    "IBM Corporation",
    "Oracle Corporation",
    "General Motors Company",
    "Ford Motor Company",
    "American Express Company",
    "Mastercard Incorporated",
    "Sony Group Corporation",
    "Toyota Motor Corporation",
    "Nestle S.A.",
    "Unilever PLC",
    "Johnson Controls International plc",
    "L'Oréal S.A.",
    "Siemens AG",
    "Merck & Co., Inc.",
    "Novartis International AG",
    "Bayer AG",
    "Royal Dutch Shell plc",
    "BP p.l.c.",
    "TotalEnergies SE",
    "Exxon Mobil Corporation",
    "Chevron Corporation",
    "Saudi Aramco",
    "BHP Group",
    "Rio Tinto Group",
    "TechCraft Solutions", "EcoGreen Innovations", "AlphaMatrix Enterprises", "Infinite Insights Co.",
    "SwiftSync Technologies", "Pinnacle Ventures", "Global Fusion Solutions", "BlueWave Innovations",
    "Stratosphere Solutions", "NexGen Dynamics", "SummitSpark Innovations", "Catalyst Creations",
    "Zenith Innovators", "Quantum Leap Ventures", "InnovateHub Solutions", "Vertex Visions Co.",
    "AccelerateX Enterprises", "ProActive Dynamics", "AgileMinds Innovations", "ElevateTech Solutions",
    "Skyline Synergy Ventures", "InnoSphere Technologies", "Nimbus Nexus Co.", "Apex Fusion Innovations",
    "TechPulse Dynamics", "FutureForge Enterprises", "OptiCore Innovations", "Synergetic Solutions",
    "InsightCraft Ventures", "StriveSync Technologies", "EvolveElite Innovations", "VivaVox Dynamics",
    "MindSpark Innovations", "InfinitiQuest Solutions", "SynthWave Enterprises", "EcoScape Innovations",
    "PentaPulse Technologies", "QuantumQuotient Ventures", "TechTraverse Dynamics", "Nexify Innovations",
    "VistaVortex Solutions", "InnovateIQ Ventures", "CatalystCraft Innovations", "FusionFlare Dynamics",
    "ZenithQuest Enterprises", "SummitShift Technologies", "AgileWave Innovations", "ElevateTech Dynamics",
    "StriveSphere Ventures", "ApexCraft Innovations", "InnoVista Technologies", "NimbusNest Dynamics",
    "ProActiveHub Ventures", "TechNucleus Innovations", "FutureFlare Solutions", "SynergeticSpark Co.",
    "VivaVista Innovations", "MindMatrix Dynamics", "InfinitiShift Ventures", "SynthCraft Innovations",
    "EcoVortex Technologies", "PentaQuest Solutions", "QuantumForge Enterprises", "TechTraverse Innovations",
    "NexGen Nexus Dynamics", "VistaForge Solutions", "InnovateElite Innovations", "CatalystSynergy Ventures",
    "FusionPulse Dynamics", "ZenithVortex Innovations", "SummitCraft Enterprises", "AgileFlare Innovations",
    "ElevateSphere Ventures", "Stratosphere Innovations", "NexifyCraft Technologies", "ProActiveQuotient Dynamics",
    "InsightPulse Innovations", "EvolveElite Solutions", "VivaCraft Ventures", "MindSphere Innovations",
    "InfinitiCraft Technologies", "SynthSync Dynamics", "EcoForge Ventures", "PentaShift Innovations",
    "QuantumElite Technologies", "TechNest Dynamics", "FutureFlare Innovations", "SynergeticSpark Ventures",
]

    return random.choice(names)
